spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIGSERVER_URI}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh/